---
#
# Gitlab CI pipeline for systematic-cli module
#

image:
  name: hiletuohela/ci:latest

stages:
  - ci-tests

lint:
  stage: ci-tests
  script:
    - pip3 install git+https://git.tuohela.net/systematic-components/systematic-cli.git@20200413.2
    - make lint

unittest:
  stage: ci-tests
  script:
    - make test

  artifacts:
    paths:
      - coverage.xml
    reports:
      junit: coverage.xml
